### ISSUE TITLE
Change logs to UTC date and add AM/PM (or 24-hour format)

### ISSUE THREAD

**Issue by Californ1a** [dreadnip/runelogs#1]
As-is, the left side pane of dates seems to use UTC time (at 0:00 game time, viewing a profile will go to the "next" day), but the logs on the individual date pages use local time. This is confusing and leads to situations like this:
![](https://i.imgur.com/t9pylxk.png)
(10pm local time on the 21st, and 5pm local time on the 22nd, or 2am 22nd utc and 9pm 22nd utc)
Where it appears like the logs occurred on different days in local time, but occurred on the same day in UTC (and thus end up on the same date page).

This can be changed on the display end by changing this line:
https://github.com/dreadnip/runelogs/blob/master/public/js/script.js#L33
to this:
```js
logTimestamp.appendChild(document.createTextNode(moment.unix(log.lg_ts).utc().format("MMMM D, YYYY hh:mm A")));
```
(`A` at the end for AM/PM, or alternatively `HH:mm` for 24hr format) Which I was going to just send a PR for, but I don't know if this would also require a change on your backend stuff as well, storing the logs, so I'm making an issue instead.

**Comment by dreadnip** [comment]
Good catch. I completely missed the formatting of those dates. I've added the UTC code you proposed but opted for a 24h format instead of AM/PM. See https://github.com/dreadnip/runelogs/commit/ecd88da2642293514301460aaab09d1ad8664bcf
