### ISSUE TITLE
Profile no longer available

### ISSUE THREAD

**Issue by Californ1a** [dreadnip/runelogs#2]
Typing in my username on the homepage "Californ1a" goes to https://runelo.gs/californ+a instead of https://runelo.gs/californ1a and even if I manually go to the correct url, it's no longer available even though my advent log/runemetrics is still, and always has been, public.

I'd assume this has something to do with it, not checking for numbers or underscores (+maybe a couple other special characters?) in the username:
https://github.com/dreadnip/runelogs/blob/5a211fb1ed9fdfd4ef4f342e5222e94aa0e0f554/src/controller.php#L409

**Comment by dreadnip** [comment]
Yeah I fucked up that regex to not include numbers. Dumb mistake.

Sadly I'm currently in Japan with no access to a computer, so this won't get fixed for a while.. sorry!

**Comment by dreadnip** [comment]
Should be fixed
